### ISSUE TITLE
loggerがエラー落ちで無限再起動ループしてる

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/slack-patron#51]
よくないね

```
Puma starting in single mode...
* Puma version: 5.6.4 (ruby 2.7.2-p137) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 1
* Listening on http://0.0.0.0:9293
Use Ctrl-C to stop
reaction has added
reaction has added
loading messages from live-comment
/usr/local/bundle/gems/slack-ruby-client-1.1.0/lib/slack/web/faraday/response/raise_error.rb:19:in `on_complete': channel_not_found (Slack::Web::Api::Errors::ChannelNotFound)
  from /usr/local/bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:18:in `block in call'
  from /usr/local/bundle/gems/faraday-2.3.0/lib/faraday/response.rb:42:in `on_complete'
  from /usr/local/bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
  from /usr/local/bundle/gems/faraday-2.3.0/lib/faraday/request/url_encoded.rb:25:in `call'
  from /usr/local/bundle/gems/faraday-multipart-1.0.4/lib/faraday/multipart/middleware.rb:28:in `call'
  from /usr/local/bundle/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
  from /usr/local/bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
  from /usr/local/bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:281:in `post'
  from /usr/local/bundle/gems/slack-ruby-client-1.1.0/lib/slack/web/faraday/request.rb:25:in `request'
  from /usr/local/bundle/gems/slack-ruby-client-1.1.0/lib/slack/web/faraday/request.rb:11:in `post'
  from /usr/local/bundle/gems/slack-ruby-client-1.1.0/lib/slack/web/api/endpoints/conversations.rb:126:in `conversations_history'
  from /usr/local/slack-patron/lib/slack.rb:49:in `conversations_history'
  from /usr/local/slack-patron/lib/slack_logger.rb:66:in `fetch_history'
  from /usr/local/slack-patron/lib/slack_logger.rb:88:in `block in start'
  from /usr/local/bundle/gems/mongo-2.17.1/lib/mongo/collection/view/iterable.rb:86:in `block in each'
  from /usr/local/bundle/gems/mongo-2.17.1/lib/mongo/cursor.rb:169:in `block in each'
  from /usr/local/bundle/gems/mongo-2.17.1/lib/mongo/cursor.rb:167:in `loop'
  from /usr/local/bundle/gems/mongo-2.17.1/lib/mongo/cursor.rb:167:in `each'
  from /usr/local/bundle/gems/mongo-2.17.1/lib/mongo/collection/view/iterable.rb:85:in `each'
  from /usr/local/slack-patron/lib/slack_logger.rb:86:in `start'
  from logger/logger.rb:10:in `<main>'
```

**Comment by hakatashi** [comment]
もしかして最近サーバーが重いのもこれが原因だったりする?
